# Generated by Django 4.2.9 on 2026-04-03 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('credential_harvest', 'Credential Harvest'), ('malware', 'Malware'), ('business_email', 'Business Email Compromise'), ('social_engineering', 'Social Engineering')], max_length=50)),
                ('subject', models.CharField(max_length=300)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField(blank=True)),
                ('landing_page_html', models.TextField(blank=True)),
                ('is_global', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='tenants.tenant')),
            ],
            options={
                'db_table': 'email_templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
