# Generated by Django 4.2.9 on 2026-04-03 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='targetimport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='targetimport',
            name='imported_targets',
            field=models.ManyToManyField(blank=True, related_name='imports', to='campaigns.target'),
        ),
        migrations.AddField(
            model_name='targetimport',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_imports', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='targetgroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_target_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='targetgroup',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='groups', to='campaigns.target'),
        ),
        migrations.AddField(
            model_name='targetgroup',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_groups', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='target',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='target',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='landingpageattachment',
            name='landing_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='campaigns.landingpage'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='template',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landing_page', to='templates.emailtemplate'),
        ),
        migrations.AddField(
            model_name='captureddata',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_data', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='captureddata',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_data', to='campaigns.target'),
        ),
        migrations.AddField(
            model_name='captureddata',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, help_text='Users who have viewed this captured data', related_name='viewed_captured_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignevent',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates.emailtemplate'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='attachmentdownload',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='campaigns.landingpageattachment'),
        ),
        migrations.AddField(
            model_name='attachmentdownload',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_downloads', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='attachmentdownload',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.target'),
        ),
        migrations.AddIndex(
            model_name='targetimport',
            index=models.Index(fields=['tenant', '-created_at'], name='target_impo_tenant__019c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='targetimport',
            index=models.Index(fields=['status'], name='target_impo_status_be2472_idx'),
        ),
        migrations.AddIndex(
            model_name='targetgroup',
            index=models.Index(fields=['tenant', 'name'], name='target_grou_tenant__694723_idx'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['tenant', 'email'], name='targets_tenant__549aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['tenant', 'status'], name='targets_tenant__8a186a_idx'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['source', 'source_id'], name='targets_source_4dd68b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='target',
            unique_together={('tenant', 'email')},
        ),
        migrations.AddIndex(
            model_name='captureddata',
            index=models.Index(fields=['campaign', '-timestamp'], name='captured_da_campaig_9e2417_idx'),
        ),
        migrations.AddIndex(
            model_name='captureddata',
            index=models.Index(fields=['target_email'], name='captured_da_target__c2a68d_idx'),
        ),
        migrations.AddIndex(
            model_name='captureddata',
            index=models.Index(fields=['timestamp'], name='captured_da_timesta_ceafd5_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignevent',
            index=models.Index(fields=['campaign', '-timestamp'], name='campaign_ev_campaig_962c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignevent',
            index=models.Index(fields=['target_email', '-timestamp'], name='campaign_ev_target__ed303f_idx'),
        ),
        migrations.AddIndex(
            model_name='attachmentdownload',
            index=models.Index(fields=['campaign', '-timestamp'], name='attachment__campaig_9efdc6_idx'),
        ),
        migrations.AddIndex(
            model_name='attachmentdownload',
            index=models.Index(fields=['target_email'], name='attachment__target__abe206_idx'),
        ),
        migrations.AddIndex(
            model_name='attachmentdownload',
            index=models.Index(fields=['attachment'], name='attachment__attachm_93ad96_idx'),
        ),
    ]
